---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: zicaentu/netology-hvac:1.2.3
        env:
        - name: VAULT_URL
          valueFrom:
            secretKeyRef:
              name: secenv
              key: vault_url
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: secenv
              key: vault_token
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

