apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: stage
spec:
  serviceName: db
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: db
          image: postgres:13-alpine
          volumeMounts:
            - name: db-pvc
              mountPath: /data
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: news
            - name: PGDATA
              value: /data
  volumeClaimTemplates:
    - metadata:
        name: db-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi