apiVersion: v1
kind: Service
metadata:
  name: fb-app-svc
  namespace: stage
spec:
  selector:
    app: fb-app
  ports:
    - name: front
      port: 80
      targetPort: 80
      protocol: TCP
    - name: back
      port: 9000
      targetPort: 9000
      protocol: TCP