apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "frontend.fullname" . }}-pvc
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.volumes.storageclass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumes.storagecapacity }}