apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: prod
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi