apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: jrecord/nettools:latest
          imagePullPolicy: IfNotPresent
          command:
            - sleep
            - "3600"
          env:
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysecret-env
                  key: username
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret-env
                  key: password
          volumeMounts:
            - name: test-secrets
              mountPath: "/app"
              readOnly: true
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: test-secrets
          secret:
            secretName: mysecret-cfg
