---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret-env
type: Opaque
data:
  username: dXNlcg==
  password: cGFzcw==

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret-cfg
type: Opaque
stringData:
  config.yaml: |
    apiUrl: "https://my.api.com/api/v1"
    username: <user>
    password: <password>
