$number_of_nodes = 2

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 512
    vb.cpus = 1
    vb.check_guest_additions = false
  end
  
  (1..$number_of_nodes).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.network "private_network", ip: "192.168.111.#{110+i}"
      node.vm.hostname = "node#{i}"
    end
  end

  $id_rsa_pub = File.read("#{Dir.home}/.ssh/id_rsa.pub")
  config.vm.provision "copy ssh public key", type: "shell",
    inline: "echo \"#{$id_rsa_pub}\" >> /home/vagrant/.ssh/authorized_keys"

end
